### PR TITLE
fix(patron-profile): fix stale contributors when switching organisations

### LINKED ISSUE #4020: Public patron profile: reload contributors when switching organisations
### Bug description:

If a patron is a member of two organisations and has items checked out in both, switching orgs from their patron profile (public) reloads the list of documents "on loan" but not the contributor field. The contributor of documents in the second organisation are from the items checked out in the first org.

Image

### Expected behavior:

Switching organisations in the patron profile should reload everything, including document contributors.

### Steps to Reproduce:

1. Check out an item to simonetta in organisation Ministry of Magic (use librarian "irma")
2. Log in as simonetta and go to "My account"
3. Switch to "Libraries of Ministry of magic"
4. See that the contributor is incorrect

### PR DESCRIPTION
**Pull request by PascalRepond**
Closes https://github.com/rero/rero-ils/issues/4020.

Updates dependencies.

When a multi-org patron switched organisations on their profile, the list of loaned documents was reloaded but the contributor field kept showing data from the first org. This happened because Angular reused the PatronProfileDocumentComponent instances (track $index) and only updated the @Input, while ngOnInit — the only place the document was fetched — was never called again.

Refactor the component to use Angular 19 signal inputs (input()) and replace the imperative ngOnInit/ngOnChanges lifecycle with a reactive toSignal(toObservable(record).pipe(switchMap(...))) chain. The switchMap automatically cancels any in-flight request and re-fetches the document whenever the record input changes, fixing the stale data.

### CODE REVIEW

**Comment by PascalRepond** [comment]
@coderabbitai review

File: projects/public-search/src/app/patron-profile/patron-profile-document/patron-profile-document.component.ts [hunk 1]
```diff
@@ -14,27 +14,37 @@
...
     selector: 'public-search-patron-profile-document',
     templateUrl: './patron-profile-document.component.html',
     standalone: false
 })
-export class PatronProfileDocumentComponent implements OnInit {
+export class PatronProfileDocumentComponent {
 
-  private patronProfileMenuService: PatronProfileMenuService = inject(PatronProfileMenuService);
-  private recordService: RecordService = inject(RecordService);
+  private patronProfileMenuService = inject(PatronProfileMenuService);
```
Comment (jma) [inline projects/public-search/src/app/patron-profile/patron-profile-document/patron-profile-document.component.ts]: Usually we keep the type to help the editor on autocompletion.

**Review by jma — APPROVED** [review]
